spring.application.name=accessible-job-manager
server.port=8060
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2.client=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.security.oauth2=TRACE
spring.devtools.add-properties=false

spring.datasource.url=${MANAGER_DB_URL:jdbc:postgresql://localhost:5432/manager}
spring.datasource.username=${MANAGER_DB_USER:exporter}
spring.datasource.password=${MANAGER_DB_PASSWORD:exporter}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.data.jpa.repositories.enabled=true


#spring.security.oauth2.client.registration.authentik.client-id=spring-boot-client
#spring.security.oauth2.client.registration.authentik.client-secret=spring-boot-client
#spring.security.oauth2.client.registration.authentik.client-authentication-method=client_secret_basic
#spring.security.oauth2.client.registration.authentik.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.authentik.scope=openid, email, profile
#spring.security.oauth2.client.registration.authentik.redirect-uri=http://localhost:8060/login/oauth2/code/authentik
#
#spring.security.oauth2.client.provider.authentik.issuer-uri=http://localhost:9000/application/o/spring-boot-client/

spring.security.oauth2.client.registration.authentik.client-id=Exporter
spring.security.oauth2.client.registration.authentik.client-secret=weszuk-5sakki-doqneG
spring.security.oauth2.client.registration.authentik.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.authentik.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authentik.scope=openid, email, profile
spring.security.oauth2.client.registration.authentik.redirect-uri=http://localhost:8060/login/oauth2/code/authentik

spring.security.oauth2.client.provider.authentik.issuer-uri=https://sso.verbis.dkfz.de/application/o/exporter-test/

#spring.security.oauth2.client.registration.authentik.client-id=4e04c6da-9afc-4991-9dde-15989812a22f
#spring.security.oauth2.client.registration.authentik.client-secret=77t8Q~9TwvJUhzvk-yxnef1uualmaAqTPl4VJcj3
#spring.security.oauth2.client.registration.authentik.client-authentication-method=client_secret_basic
#spring.security.oauth2.client.registration.authentik.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.authentik.scope=openid, email, profile
#spring.security.oauth2.client.registration.authentik.redirect-uri=http://localhost:8060/login/oauth2/code/authentik

#spring.security.oauth2.client.provider.authentik.issuer-uri=https://login.microsoftonline.com/c5ede864-10a1-4ccf-8994-7e352a5186ea/v2.0
