apiVersion: v1
kind: Service
metadata:
  name: {{ include "ajm.fullname" . }}
  labels: {{- include "ajm.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.ajm.service.type }}
  ports:
    - name: http
      port: {{ .Values.ajm.service.port }}
      targetPort: http
  selector:
    {{- include "ajm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
